Compatibility with cstruct v4
fox-it/dissect.etl pull request #29
Opened 2024-05-27 12:10 UTC by Miauwkeru

Closes #23

2024-05-27 12:16 UTC, Schamper submitted a review, later dismissed

2024-05-27 12:16 UTC, Schamper commented on dissect/etl/headers/event.py
> +    def __init__(self, payload: memoryview):
```suggestion
    def __init__(self, payload: bytes):
```
I don't think it's restricted to a memoryview?

2024-05-27 12:16 UTC, Schamper commented on dissect/etl/headers/headers.py
> +    ETL = "ETL"
What is this necessary for?

2024-05-27 12:16 UTC, Schamper commented on dissect/etl/headers/headers.py
> +    def __init__(self, marker: Marker, data: memoryview, etl: ETL):
```suggestion
    def __init__(self, marker: Marker, data: bytes, etl: ETL):
```

2024-05-27 12:16 UTC, Schamper commented on dissect/etl/headers/headers.py
> +    def __init__(self, marker: Marker, data: memoryview, etl: ETL):
```suggestion
    def __init__(self, marker: Marker, data: bytes, etl: ETL):
```

2024-05-27 12:16 UTC, Schamper commented on dissect/etl/utils.py
> +c_etl_global = cstruct().load(c_global_def)
```suggestion
c_etl_global = cstruct().load(global_def)
```

2024-05-27 12:16 UTC, Schamper commented on dissect/etl/utils.py
> +c_etl_headers = cstruct().load(c_etl_definitions)
```suggestion
c_etl_headers = cstruct().load(etl_def)
```

2024-05-27 12:30 UTC, pyrco requested changes
The `Structure` return types in `system.py` could also be made more specific.

2024-05-27 12:30 UTC, pyrco commented on dissect/etl/headers/headers.py
>      def _header_type(self) -> Structure:
```suggestion
    def _header_type(self) -> c_etl_headers.MessageHeader:
```

2024-05-27 12:30 UTC, pyrco commented on dissect/etl/headers/headers.py
>      def _header_type(self) -> Structure:
The other `Structure` types below can also be made more specific.

Given `ErrorHeader._header_type()` returns `None`, the base class `Header._header_type()` return type should probably be changeds to `Structure | None`.

2024-05-30 14:32 UTC, pyrco approved these changes

2024-06-04 12:14 UTC, merged